ASTRA_DB_DATABASE_ID=
ASTRA_DB_REGION=
ASTRA_DB_NAMESPACE=
OPENAI_API_KEY=

AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_API_KEY=
LANGCHAIN_ENDPOINT =
LANGCHAIN_API_KEY =
LANGCHAIN_PROJECT =


ASTRA_DB_ENDPOINT=
ASTRA_DB_APPLICATION_TOKEN=